FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
MAINTAINER {{ maintainer }}

{% if base_distro in ['ubuntu', 'debian'] %}

COPY cassandra.list /etc/apt/sources.list.d/cassandra.list

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv 514A2AD631A57A16DD0047EC749D6EEC0353B12C \
  && apt-get update \
  && apt-get install -y --no-install-recommends cassandra \
  && apt-get clean

{% endif %}
